spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring-practice-sql
    username: root
    password: spring-practice-sql
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      connection-url: jdbc:mysql://localhost:3306/spring-practice-sql
      dialect: org.hibernate.dialect.MySQLDialect
